services:
  - type: web
    name: energc-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: API_KEY
        sync: false
      - key: PORT
        value: 3000
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free 