services:
  - type: web
    name: energc
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 8080 